export { default as Home } from '../pagesTwo/Home/Home'
export { default as Products } from '../pagesTwo/Products/Products'
export { default as Product } from '../pagesTwo/Product/Product'
export { default as Users } from '../pagesTwo/Users/Users'
export { default as Login } from '../pagesTwo/Login/Login'
