export { default as Home } from './home/Home'
export { default as About } from './About/About'
export { default as Blog } from './Blog/Blog'
export { default as Contact } from './Contact/Contact'
export { default as Gallery } from './Gallery/Gallery'
export { default as Post } from './Post/Post'
export { default as SignIn } from './SignIn/SignIn'
export { default as ErrorPage } from './ErrorPage/ErrorPage'