export {default as Home} from "./Home/Home"
export {default as Portfolio} from "./Portfolio/Portfolio"
export {default as AboutUs} from "./AboutUs/AboutUs"
export {default as Blog} from "./Blog/Blog"
export {default as Contact} from "./Contact/Contact"
export {default as ErrorPage} from "./ErrorPage/ErrorPage"