export const ADD_COUNT = 'ADD_COUNT'
export const MINUS_COUNT = 'MINUS_COUNT'
export const RESET_COUNT = 'RESET_COUNT'
export const ADD_ITEM = 'ADD_ITEM'
export const SET_TEN = 'SET_TEN'
export const SORT = 'SORT'
export const DELETE_BY_INDEX = 'DELETE_BY_INDEX'
